### ISSUE TITLE
WATCHER_TICK_DELAY does not have default value in example.env

### ISSUE THREAD

**Issue by joshfeld** [RedSkiesReaperr/notion-igdb-autocomplete#1]
WATCHER_TICK_DELAY is a required env variable but has nothing set in example.env. A recommended default value would be nice as well for this

**Comment by RedSkiesReaperr** [comment]
Yes you right, i forget it.. fixed [by this commit](https://github.com/RedSkiesReaperr/notion-igdb-autocomplete/commit/d5b17c2e700437f188f9a54b28a93a8050db7413).

I put 3 seconds delay as default, so it does not spam requests while maintaining a smooth experience.
