### ISSUE TITLE
Release date is not a property that exists

### ISSUE THREAD

**Issue by Lunarethic** [RedSkiesReaperr/notion-igdb-autocomplete#4]
Im running into a problem running the program, its connected to my notion fine but it seems to fail querying from IGDB. Im running it through docker, Logs below:

2024/09/11 22:03:47 [651c9802-40f2-4bbb-9f5a-cf184a75340d] Starting
2024/09/11 22:03:47 [0efddd47-43c6-4a0f-a770-c8e8b0763bbb] Starting
2024/09/11 22:03:47 [651c9802-40f2-4bbb-9f5a-cf184a75340d] Searching game...
2024/09/11 22:03:47 [0efddd47-43c6-4a0f-a770-c8e8b0763bbb] Searching game...
2024/09/11 22:03:48 [651c9802-40f2-4bbb-9f5a-cf184a75340d] 7 games found: 'Starfield', 'Starfield Wars', 'Starfield: Rev-8', 'Starfield: Shattered Space', 'Starfield: Premium Edition', 'Starfield: Constellation Edition''Starfield Digipick-Locking Minigame Simulator'
2024/09/11 22:03:48 [651c9802-40f2-4bbb-9f5a-cf184a75340d] Chosen game: 'Starfield'
2024/09/11 22:03:48 [651c9802-40f2-4bbb-9f5a-cf184a75340d] Updating Notion page...
2024/09/11 22:03:48 [0efddd47-43c6-4a0f-a770-c8e8b0763bbb] 1 games found: 'Zenless Zone Zero'
2024/09/11 22:03:48 [0efddd47-43c6-4a0f-a770-c8e8b0763bbb] Chosen game: 'Zenless Zone Zero'
2024/09/11 22:03:48 [0efddd47-43c6-4a0f-a770-c8e8b0763bbb] Updating Notion page...
2024/09/11 22:03:48 [0efddd47-43c6-4a0f-a770-c8e8b0763bbb] task resume:
....Id=
....Type=GameInfos
....Status=Finished
....Query='Zenless Zone Zero'
....NotionId=
....Error=Release date is not a property that exists.
....CreatedAt=2024-09-11 22:03:47
....QueuedAt=2024-09-11 22:03:47
....StartedAt=2024-09-11 22:03:47
....EndedAt=2024-09-11 22:03:48

**Comment by RedSkiesReaperr** [comment]
Can you confirm your database is set up as explained in the [configuration guide](https://github.com/RedSkiesReaperr/notion-igdb-autocomplete?tab=readme-ov-file#2-create-a-notion-database) ? Especially for the "Release date" property and its type "Date"

**Comment by Lunarethic** [comment]
your reply made me realize the API is looking for "Release date" instead of "Release Date" that I put with the capital D.
All is good now!
